### PR TITLE
attempt to fix issue #32

### LINKED ISSUE #32: to_netcdf_throttled fails with newer xarray version.
Since the latest update to the stable conda module, we got two errors with climtas storing files, here's one:

```
Traceback (most recent call last):
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-22.04/bin/era5grib", line 10, in <module>
    sys.exit(main())
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-22.04/lib/python3.9/site-packages/era5grib/era5grib.py", line 341, in main
    func(**dargs)
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-22.04/lib/python3.9/site-packages/era5grib/era5grib.py", line 177, in era5grib_wrf
    save_grib(ds, output, format=format)
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-22.04/lib/python3.9/site-packages/era5grib/era5grib.py", line 55, in save_grib
    climtas.io.to_netcdf_throttled(ds, tmp_compressed)
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-22.04/lib/python3.9/site-packages/climtas/io.py", line 89, in to_netcdf_throttled
    f = ds.to_netcdf(str(path), encoding=encoding, compute=False)
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-22.04/lib/python3.9/site-packages/xarray/core/dataset.py", line 1901, in to_netcdf
    return to_netcdf(
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-22.04/lib/python3.9/site-packages/xarray/backends/api.py", line 1072, in to_netcdf
    dump_to_store(
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-22.04/lib/python3.9/site-packages/xarray/backends/api.py", line 1119, in dump_to_store
    store.store(variables, attrs, check_encoding, writer, unlimited_dims=unlimited_dims)
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-22.04/lib/python3.9/site-packages/xarray/backends/common.py", line 265, in store
    self.set_variables(
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-22.04/lib/python3.9/site-packages/xarray/backends/common.py", line 303, in set_variables
    target, source = self.prepare_variable(
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-22.04/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 481, in prepare_variable
    encoding = _extract_nc4_variable_encoding(
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-22.04/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 277, in _extract_nc4_variable_encoding
    raise ValueError(
ValueError: unexpected encoding parameters for 'netCDF4' backend: ['szip', 'zstd', 'bzip2', 'blosc']. Valid encodings are: {'fletcher32', 'chunksizes', 'complevel', 'least_significant_digit', 'shuffle', 'contiguous', 'zlib', '_FillValue', 'dtype'}
```

### PR DESCRIPTION
**Pull request by HoWol76**
removes keys from encoding dictionary that are not used for netcdf interface. This should fix #32 

This is not tested. To be honest, I don't know how to test this properly.

### CODE REVIEW

**Comment by paolap** [comment]
@ScottWales and @HoWol76  I tested this by running the era5grib command that was generating the error for one of our users.

era5grib wrf --no-era5land --namelist namelist_2019_059.wps --geo geo_em.d01.nc --output out.grib

This worked so it should be ok to merge the pull request.
Scott, this is a bit urgent for us because era5grib is broken in the new environments, if you don't have time to merge and create a new release, we could use Holger fork on coecms to create a new release and a conda package for the coecms channel. However, I think this would make sense only if you are happy for us to take over the package completely.
Thanks!

**Comment by ScottWales** [comment]
@paolap I'm happy either way, feel free to move this to the coecms repo or I can add more people as maintainers. I'm unlikely to be focusing much on this repository. I'll merge the change and make a release, hopefully the automated publishing still works.

**Comment by paolap** [comment]
I tried to to build the conda package locally. There are 5 tests failing

FAILED test/test_blocked.py::test_percentile[daily_dask] - TypeError: merge_p...
FAILED test/test_blocked.py::test_percentile[daily_dask_2d] - TypeError: merg...
FAILED test/test_blocked.py::test_dask_approx_percentile - TypeError: merge_p...
FAILED daskutil.py::climtas.daskutil.graph_sizes
FAILED helpers.py::climtas.helpers.map_blocks_array_to_dataframe

I'm not sure about the last two, something to do with documentation?
The first 3 are all due to interpolation argument being deprecated:
```
interpolation str, optional
Deprecated name for the method keyword argument.
Deprecated since version 2022.1.0.
```
Easy to fix, I'm opening an issue and then I'll create an new pull_request

**Comment by paolap** [comment]
Ok, I see you've already solved this, easy :-)

**Pull request merged**
